default_language_version:
  python: python3
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.6.9'
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.4.27
  hooks:
    - id: uv-lock
    - id: uv-export
      args: ["--frozen", "--no-dev", "--no-emit-project", "--output-file=requirements.txt", "--no-hashes"]
    - id: uv-export
      args: ["--frozen", "--no-emit-project", "--output-file=dev-requirements.txt", "--no-hashes"]
ci:
  autofix_prs: true
  autoupdate_branch: develop
  autoupdate_schedule: quarterly
