version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: '3.12' # renovate: datasource=python-version depName=python
  jobs:
    post_install:
      - sphinx-apidoc -ePT --remove-old -o docs/api flexget

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
