name: Changelog Update

on:
  push:
    branches:
    - develop

permissions:
  contents: read

jobs:
  update-changelog:
    permissions:
      contents: write  # for Git to git push
    name: Update Changelog
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        repository: Flexget/wiki
        path: wiki
        token: ${{ secrets.flexgetbot_pat }}
        ref: main
    - name: Setup Git User
      run: |
        git config --global user.email ${{ secrets.git_email }}
        git config --global user.name ${{ secrets.git_user }}
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.27"
        enable-cache: true
        cache-dependency-glob: 'uv.lock'
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dev dependencies
      run: |
        uv sync --only-dev
    - name: Update the Changelog
      run: |
        set -x
        uv run --no-project update-changelog.py wiki/ChangeLog.md
        cd wiki
        git add ChangeLog.md
        if ! git diff --cached --exit-code; then
            git commit -m "Automated ChangeLog update"
            git push origin main
        fi
