name: Trigger Deploy

on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch: {}

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Status
        run: |
          commit_state=$(curl -sf -H 'Accept: application/json' 'https://github.com/${{ github.repository }}/commits/deferred_commit_data/${{ github.ref_name }}' | jq -r '.deferredCommits[0].statusCheckStatus.state // "not_found"')
          if [[ "$commit_state" != "success" ]]; then
            echo "::error::Status is '$commit_state'."
            exit 1
          fi
      - name: Create Deployment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          github-token: ${{ secrets.flexgetbot_pat }}
          script: |
            await github.rest.repos.createDeployment({
              ...context.repo,
              ref: context.ref.slice(11),
              required_contexts: []
            });
