name: Trigger Deploy

on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch: {}

permissions: {}

jobs:
  deploy:
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Create Deployment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          github-token: ${{ secrets.flexgetbot_pat }}
          script: |
            await github.rest.repos.createDeployment({
              ...context.repo,
              ref: context.ref.slice(11),
            });
