name: Build and release to PyPI
on: ['deployment']
permissions: {}
jobs:
  release:
    permissions:
      contents: write # for git push
      deployments: write # to create a deployment status

    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        token: ${{ secrets.flexgetbot_pat }}
        fetch-depth: 0
    - name: Setup Git User
      run: |
        git config user.email ${{ secrets.git_email }}
        git config user.name ${{ secrets.git_user }}
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        # Install a specific version of uv.
        version: "0.4.27"
        enable-cache: true
        cache-dependency-glob: 'uv.lock'
    - name: Install dev dependencies
      run: |
        uv sync --only-group release --frozen
    - name: Set Deployment Status Pending
      uses: justacodename/deployment-status@v2
      with:
        state: pending
    - name: Run release script
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.pypi_token }}
      run: |
        ./release.sh
    - name: Build Changelog
      id: changelog
      if: env.release_tag
      run: |
        echo 'CHANGELOG_BODY<<EOF' >> $GITHUB_ENV
        uv run --no-project dev_tools.py get-changelog ${{ env.release_tag }} >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      if: env.release_tag
      with:
        tag: ${{ env.release_tag }}
        artifacts: "dist/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{ env.CHANGELOG_BODY }}
    - name: Set Deployment Status Success
      uses: justacodename/deployment-status@v2
      with:
        state: success
    - name: Set Deployment Status Failure
      if: failure() || cancelled()
      uses: justacodename/deployment-status@v2
      with:
        state: failure
